name: skaara
description: "A flutter local proxy for offline HTTP operations & caching"
version: 0.0.6
homepage: https://github.com/owlnext-fr/skaara
repository: https://github.com/owlnext-fr/skaara

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1
  path_provider: ^2.1.2
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.9
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8

flutter:
