# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # tag pattern on pub.dev: 'v{{version}'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      # checkout project
      - uses: actions/checkout@v3
      # setup dart
      - uses: dart-lang/setup-dart@v1
      # setup flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      # install dependencies
      - name: Install dependencies
        run: flutter pub get
      # run tests
      - name: Run tests
        run: flutter test
      # build package
      - name: Build
        run: flutter pub publish --dry-run
      # publish package
      - name: Publish
        run: flutter pub publish --force
